GET http://localhost:5000/api/recipes

###

POST http://localhost:5000/api/recipes 
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###
GET http://localhost:5000/api/recipes/6340342daa988cf9d50d0f4d

###
PUT http://localhost:5000/api/recipes/63403833a4ae96346d8fea1b
content-type: application/json

{   
    "$set":{
        "name": "spl",
        "ingredients": [{"EQ":"Wed, 21 Oct 2015 18:27:50 GMT"}, {"eq":"algo"}],
        "instructions": ["fsaf",
        "Shake well and pour in a highballglass"]    
    }
}


###
DELETE http://localhost:5000/api/recipes/633dbf9d097ae82c829337e5


###
GET http://localhost:5000/RecipeList


###
POST http://localhost:5000/RecipeList
content-type: application/json

{
    "name": "sample",
    "ingredients": [{"EQ":"Wed, 21 Oct 2015 18:27:50 GMT"}, {"eq":"algo"}],
    "instructions": ["Wed, 21 Oct 2015 18:27:50 GMT",
      "Shake well and pour in a highballglass"]

}

###
GET http://localhost:5000/Recipe/6340342daa988cf9d50d0f4d

###
DELETE http://localhost:5000/Recipe/63403833a4ae96346d8fea1b


###
PUT http://localhost:5000/Recipe/63403833a4ae96346d8fea1b
content-type: application/json

{
    "$set":{
        "name": "sample2",
        "ingredients": "algo",
        "instructions": ["wtf",
        "Shake well and pour in a highballglass"]
    }

}