# Generated by Django 4.1.1 on 2022-11-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_alter_ingrediente_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta'),
        ),
    ]
